# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
      
    #- name: test
     # run: ssh ec2-user@18.163.215.160 'touch atsetfile'
    - name: ls
      run: ls
    
    - name: backup file
      run: ssh ec2-user@18.163.215.160 'sudo tar -cvf hugobackup/hugo_$(date "+%Y-%m-%d_%H:%M:%S").tar.gz /www/hugo/content && sudo rm -rf /www/hugo/content ' 
    
    - name: scp
      run: scp ./content ec2-user@18.163.215.160:/www/hugo
    
    - name: make 
      run: ssh ec2-user@18.163.215.160 'cd /www/hugo && sudo ./hugo'
